version: '3'

networks:
  storefront-application: {}

services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    restart: always
    networks:
      - storefront-application

  node:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
    environment:
      - NITRO_HOST=node
      - NITRO_PORT=3000
      - NITRO_SSL_CERT=${SSL_CERT}
      - NITRO_SSL_KEY=${SSL_KEY}
      - NUXT_STOREFRONT_STORAGE_CACHE_HOST=redis
      - NUXT_STOREFRONT_STORAGE_SESSION_HOST=redis
    ports:
      - '3000:3000'
    profiles:
      - node
    restart: always
    volumes:
      - ./.env:/app/.env
    networks:
      - storefront-application
